Sudo Commands Bundle terraform support
okta/terraform-provider-oktapam pull request #131
Opened 2024-05-22 20:01 UTC by UlfatSayyed-okta

2024-06-17 21:17 UTC, SajanAlexander-okta requested changes

2024-06-17 21:17 UTC, SajanAlexander-okta commented on oktapam/resource_sudo_commands_bundle.go
> +	// there isn't a true delete with password settings, and as databases don't specify ManagedPrivilegedAccounts,
is this comment relevant?

2024-06-17 21:17 UTC, SajanAlexander-okta commented on oktapam/resource_sudo_commands_bundle_test.go
> +			command       = "/bin/run.sh"
there are a lot of other attributes that are on this resource - could we get some better coverage?  doesn't have to be everything.  also, when adding more attributes, please be sure to check them for their presence and correctness within the tests.

2024-06-17 21:17 UTC, SajanAlexander-okta commented on oktapam/resource_sudo_commands_bundle_test.go
> +	resource.Test(t, resource.TestCase{
we generally try and run both a create and update for resources when doing a test.

2024-06-20 07:08 UTC, UlfatSayyed-okta commented on go.mod
> +	github.com/atko-pam/pam-sdk-go v1.0.70-0.20240605060748-0f7af3861a5e
Yes, this is in pending review, have it here to prove it's tested. I can change it once that's merged.

2024-06-20 07:14 UTC, UlfatSayyed-okta commented on go.mod
> +	github.com/atko-pam/pam-sdk-go v1.0.70-0.20240605060748-0f7af3861a5e
pam-sdk PR https://github.com/atko-pam/pam-sdk-go/pull/64 and the spec PR https://github.com/atko-pam/platform/pull/8512

2024-06-20 07:32 UTC, UlfatSayyed-okta commented on oktapam/data_source_sudo_commands_bundles_test.go
> +				Config: fmt.Sprintf("%s\n%s", initConfig, list1Config),
Done

2024-07-03 12:55 UTC, UlfatSayyed-okta commented on go.mod
> +	github.com/atko-pam/pam-sdk-go v1.0.70-0.20240605060748-0f7af3861a5e
Now using  https://github.com/atko-pam/pam-sdk-go/releases/tag/v1.0.72

2024-07-10 16:46 UTC, UlfatSayyed-okta commented on oktapam/client/sudo_command_bundle.go
> +	request := sdkClient.SDKClient.SudoCommandsAPI.ListSudoCommandBundles(ctx, sdkClient.Team)
@SajanAlexander-okta - I was looking into adding support for pagination here but I see the generated sudo command bundle request [does not have](https://github.com/atko-pam/pam-sdk-go/blob/master/client/pam/api_sudo_commands.go#L259) the pagination-related fields like [ListSecrets has](https://github.com/atko-pam/pam-sdk-go/blob/master/client/pam/api_secrets.go#L666). Should I manually add it to the sdk or am I missing something?

2024-07-10 17:32 UTC, SajanAlexander-okta commented on oktapam/client/sudo_command_bundle.go
> +	request := sdkClient.SDKClient.SudoCommandsAPI.ListSudoCommandBundles(ctx, sdkClient.Team)
So things to check: 

 - does the API itself support pagination?
 - does the open api spec define the pagination fields in the response?

2024-07-18 01:38 UTC, UlfatSayyed-okta commented
Closing this because created pull/132 with verified commmits

2024-07-18 01:38 UTC, closed without merging